# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "CI"
on:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
  pull_request:
  workflow_dispatch:
# queue jobs and only allow 1 run per branch due to the likelihood of hitting GitHub resource limits
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  buildGradle:
    name: 'Build Gradle Plugins'
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21 ]
    runs-on: ubuntu-24.04
    steps:
      - name: "Output Agent IP" # in the event RAO blocks this agent, this can be used to debug it
        run: curl -s https://api.ipify.org
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v5
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "🔨 Build project without tests"
        if: ${{ contains(github.event.head_commit.message, '[skip tests]') }}
        working-directory: 'grails-gradle'
        run: >
          ./gradlew build
          --continue
          --stacktrace
          -PskipCodeStyle
          -PskipTests
      - name: "🔨 Build project with tests"
        if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
        working-directory: 'grails-gradle'
        run: >
          ./gradlew build
          --continue
          --stacktrace
          --rerun-tasks
          -PskipCodeStyle
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    name: 'Build Grails-Core'
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21, 24 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Output Agent IP" # in the event RAO blocks this agent, this can be used to debug it
        run: curl -s https://api.ipify.org
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v5
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "🔨 Build project"
        run: >
          ./gradlew build :grails-shell-cli:installDist groovydoc
          --continue
          --rerun-tasks
          --stacktrace
          -PonlyCoreTests
          -PskipCodeStyle
  buildForge:
    name: "Build Grails Forge"
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21 ]
    runs-on: ubuntu-24.04
    steps:
      - name: "Output Agent IP" # in the event RAO blocks this agent, this can be used to debug it
        run: curl -s https://api.ipify.org
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v5
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "🔨 Build project without tests"
        if: ${{ contains(github.event.head_commit.message, '[skip tests]') }}
        working-directory: 'grails-forge'
        run: >
          ./gradlew build
          --continue
          --stacktrace
          -PskipCodeStyle
          -PskipTests
      - name: "🔨 Build project with tests"
        if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
        working-directory: 'grails-forge'
        run: >
          ./gradlew build
          --continue
          --rerun-tasks
          --stacktrace
          -PskipCodeStyle
      - name: "✅ Verify combined CLI"
        run: |
          cd grails-forge
          cp grails-cli/build/distributions/apache-grails-*.zip cli.zip
          unzip cli -d tmp1
          mv tmp1/apache-grails-* tmp1/cli
          ./tmp1/cli/bin/grails --version
          ./tmp1/cli/bin/grails-forge-cli --version
      - name: "📤 Upload CLI Zip to Workflow Summary Page"
        if: ${{ matrix.java == '17' }}
        uses: actions/upload-artifact@v4
        with:
          name: 'apache-grails-SNAPSHOT-incubating-bin.zip'
          include-hidden-files: true
          path: grails-forge/tmp1/cli/**/*
          if-no-files-found: 'error'
  functional:
    name: "Functional Tests"
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21, 24 ]
    runs-on: ubuntu-24.04
    steps:
      - name: "Output Agent IP" # in the event RAO blocks this agent, this can be used to debug it
        run: curl -s https://api.ipify.org
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v5
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "🏃 Run Functional Tests"
        run: >
          ./gradlew bootJar check
          --continue
          --rerun-tasks
          --stacktrace
          -PgebAtCheckWaiting
          -PonlyFunctionalTests
          -PskipCodeStyle
          -PskipHibernate5Tests
          -PskipMongodbTests
  mongodbFunctional:
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    name: "Mongodb Functional Tests"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21 ]
        mongodb-version: [ '7.0', '8.0' ] # test with supported versions https://www.mongodb.com/legal/support-policy/lifecycles
    steps:
      - name: "Output Agent IP" # in the event RAO blocks this agent, this can be used to debug it
        run: curl -s https://api.ipify.org
      - name: "📥 Checkout the repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v5
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY }}
      - name: "🏃 Run Functional Tests"
        env:
          GITHUB_MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: >
          ./gradlew bootJar cleanTest check
          --continue
          --rerun-tasks
          --stacktrace
          -PonlyMongodbTests
          -PmongodbContainerVersion=${{ matrix.mongodb-version }}
          -PskipCodeStyle
  hibernate5Functional:
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    name: "Hibernate5 Functional Tests"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21 ]
    steps:
      - name: "Output Agent IP" # in the event RAO blocks this agent, this can be used to debug it
        run: curl -s https://api.ipify.org
      - name: "📥 Checkout the repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v5
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY }}
      - name: "🏃 Run Functional Tests"
        env:
          GITHUB_MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: >
          ./gradlew bootJar cleanTest check
          --continue
          --rerun-tasks
          --stacktrace
          -PonlyHibernate5Tests
          -PskipCodeStyle
  publishGradle:
    if: github.repository_owner == 'apache' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    needs: [ buildGradle ]
    runs-on: ubuntu-24.04
    steps:
      - name: "Output Agent IP" # in the event RAO blocks this agent, this can be used to debug it
        run: curl -s https://api.ipify.org
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v5
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "📤 Publish Gradle Snapshot Artifacts"
        env:
          GRAILS_PUBLISH_RELEASE: 'false'
          MAVEN_PUBLISH_URL: ${{ secrets.GRAILS_NEXUS_PUBLISH_SNAPSHOT_URL }}
          MAVEN_PUBLISH_USERNAME: ${{ secrets.NEXUS_USER }}
          MAVEN_PUBLISH_PASSWORD: ${{ secrets.NEXUS_PW  }}
        working-directory: 'grails-gradle'
        run: >
          ./gradlew publish aggregateChecksums aggregatePublishedArtifacts
          --no-build-cache
          --rerun-tasks
      - name: "📤 Upload grails-gradle checksums"
        uses: actions/upload-artifact@v4
        with:
          name: grails-gradle-checksums
          path: grails-gradle/build/grails-gradle-checksums.txt
      - name: "📤 Upload grails-gradle published artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: grails-gradle-artifacts.txt
          path: grails-gradle/build/grails-gradle-artifacts.txt
  publish:
    needs: [ publishGradle, build, functional, hibernate5Functional, mongodbFunctional ]
    if: >-
      ${{ always() && 
          github.repository_owner == 'apache' && 
          (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && 
          needs.publishGradle.result == 'success' && 
          (needs.build.result == 'success' || needs.build.result == 'skipped') && 
          (needs.functional.result == 'success' || needs.functional.result == 'skipped') && 
          (needs.hibernate5Functional.result == 'success' || needs.hibernate5Functional.result == 'skipped') && 
          (needs.mongodbFunctional.result == 'success' || needs.mongodbFunctional.result == 'skipped') 
      }}
    runs-on: ubuntu-24.04
    steps:
      - name: "Output Agent IP" # in the event RAO blocks this agent, this can be used to debug it
        run: curl -s https://api.ipify.org
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v5
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "📤 Publish Grails-Core Snapshot Artifacts"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2 
        env:
          GRAILS_PUBLISH_RELEASE: 'false'
          MAVEN_PUBLISH_URL: ${{ secrets.GRAILS_NEXUS_PUBLISH_SNAPSHOT_URL }}
          MAVEN_PUBLISH_USERNAME: ${{ secrets.NEXUS_USER }}
          MAVEN_PUBLISH_PASSWORD: ${{ secrets.NEXUS_PW  }}
        with: 
          timeout_seconds: 1200 # normal range 14min if build is not cached (no tests running)
          max_attempts: 3 # Attempts to address: Could not write to resource 'https://repository.apache.org/content/repositories/snapshots/...' Read timed out
          retry_wait_seconds: 180
          command: ./gradlew publish aggregateChecksums aggregatePublishedArtifacts --no-build-cache --rerun-tasks
      - name: "📤 Upload grails-core checksums"
        uses: actions/upload-artifact@v4
        with:
          name: grails-core-checksums.txt
          path: build/grails-core-checksums.txt
      - name: "📤 Upload grails-core published artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: grails-core-artifacts.txt
          path: build/grails-core-artifacts.txt
      - name: "🔨 Create Grails Wrapper Distribution Zip"
        run: >
          ./gradlew :grails-wrapper:distZip
      - name: "✅ Verify grails-wrapper"
        if: success()
        run: |
          export GRAILS_WRAPPER_ALLOWED_TYPES='SNAPSHOT'
          cp grails-wrapper/build/distributions/apache-grails-wrapper-*.zip build/wrapper.zip
          cd build
          unzip wrapper -d tmp
          mv tmp/apache-grails-wrapper-* tmp/wrapper
          ./tmp/wrapper/grailsw --version
      - name: "📤 Upload Wrapper Zip to Workflow Summary Page"
        uses: actions/upload-artifact@v4
        with:
          name: apache-grails-wrapper-SNAPSHOT-incubating-bin
          path: tmp/wrapper
  publishForge:
    if: github.repository_owner == 'apache' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    needs: [ buildForge, publishGradle, publish ]
    runs-on: ubuntu-24.04
    steps:
      - name: "Output Agent IP" # in the event RAO blocks this agent, this can be used to debug it
        run: curl -s https://api.ipify.org
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v5
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "📤 Publish Gradle Snapshot Artifacts"
        env:
          GRAILS_PUBLISH_RELEASE: 'false'
          MAVEN_PUBLISH_URL: ${{ secrets.GRAILS_NEXUS_PUBLISH_SNAPSHOT_URL }}
          MAVEN_PUBLISH_USERNAME: ${{ secrets.NEXUS_USER }}
          MAVEN_PUBLISH_PASSWORD: ${{ secrets.NEXUS_PW  }}
        working-directory: 'grails-forge'
        run: >
          ./gradlew publish aggregateChecksums aggregatePublishedArtifacts
          --no-build-cache
          --rerun-tasks
      - name: "📤 Upload grails-forge checksums"
        uses: actions/upload-artifact@v4
        with:
          name: grails-forge-checksums
          path: grails-forge/build/grails-forge-checksums.txt
      - name: "📤 Upload grails-gradle published artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: grails-forge-artifacts.txt
          path: grails-forge/build/grails-forge-artifacts.txt
  docs:
    if: github.repository_owner == 'apache' && github.event_name == 'push'
    needs: [ publish ]
    runs-on: ubuntu-24.04
    steps:
      - name: "Output Agent IP" # in the event RAO blocks this agent, this can be used to debug it
        run: curl -s https://api.ipify.org
      - name: "📥 Checkout the repository"
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: "🔀 Store current branch name"
        run: |
          TARGET_BRANCH="${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}"
          echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV
          echo "Target Branch: ${TARGET_BRANCH}"
      - name: "📅 Set current date as env variable"
        run: |
          NOW=$(date +'%Y-%m-%dT%H%M%S')
          echo "NOW=${NOW}" >> $GITHUB_ENV
          echo "Current date: ${NOW}"
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v5
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY }}
      - name: "🔨 Build Snapshot Documentation"
        run: >
          ./gradlew grails-doc:build
          -PgithubBranch=${{ env.TARGET_BRANCH }}
      - name: "📤 Upload Generated Docs to Workflow Result Page"
        uses: actions/upload-artifact@v4
        with:
          name: grails-docs-${{ env.NOW }}.zip
          path: ./build/distributions/*.zip
          compression-level: 0 # Already a zip
      - name: "🚀 Publish to Github Pages"
        if: github.event_name == 'push'
        uses: apache/grails-github-actions/deploy-github-pages@asf
        env:
          GH_TOKEN: ${{ secrets.GRAILS_GHTOKEN }}
          GRADLE_PUBLISH_RELEASE: 'false'
          SOURCE_FOLDER: grails-doc/build/docs
          TARGET_REPOSITORY: 'apache/grails-doc'
